# Spring Boot 기본 설정
spring:
  application:
    name: monito-agent

  profiles:
    active: dev

server:
  port: 8080

logging:
  level:
    root: INFO
    com.agent.monito: DEBUG
    com.agent.monito.global.jwt.JwtTokenProvider: DEBUG