# 운영 환경 설정
spring:
  config:
    activate:
      on-profile: prod

# Docker 설정 (운영환경)
docker:
  host: ${DOCKER_HOST:unix:///var/run/docker.sock}
  tls-verify: ${DOCKER_TLS_VERIFY:false}
  cert-path: ${DOCKER_CERT_PATH:}

backend:
  websocket:
    url: ${BE_HOST:ws://localhost:8081/ws/agent/collect}
  host:
    url: tcp://localhost:8081

# JWT 설정
jwt:
  secret: ${JWT_SECRET}

# 서버 포트
server:
  port: ${SERVER_PORT:8080}

# 스케줄링 설정 (운영환경)
scheduler:
  metrics-push:
    fixed-delay: 5000      # 5초마다 실행 (밀리초)
    initial-delay: 10000   # 애플리케이션 시작 후 10초 뒤 첫 실행
  logs-push:
    fixed-delay: 3000     # 3초마다 실행 (밀리초)
    initial-delay: 5000   # 애플리케이션 시작 후 5초 뒤 첫 실행
  agent-info-push:
    fixed-delay: 3600000     # 1시간마다 실행 (3600000ms)
  thread-pool:
    core-size: 2           # 기본 스레드 수
    max-size: 5            # 최대 스레드 수
    queue-capacity: 10     # 큐 용량

# 로그 레벨 (운영환경에서는 INFO/WARN 레벨 사용)
logging:
  level:
    root: INFO
    com.agent.monito: INFO
    com.agent.monito.global.jwt.JwtTokenProvider: WARN